# Generated by Django 4.2.4 on 2023-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-datecreated']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.ManyToManyField(to='base.job'),
        ),
    ]
