# Generated by Django 4.2.4 on 2023-11-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_job_alter_profile_options_remove_profile_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
